name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: "~1.15"
      - run: |
          deno --version
          
          ./build.sh

          ./test/all.sh ./bin/pom